/**
 * Satellite imagery (Planet). Turning imagery into signal is a heavy CV/ML effort, so v1
 * delivers the high-value first step the publisher asked for: a company-specific, sector-aware
 * list of WHAT to evaluate from space and what each observation would signal for the thesis —
 * generated by Claude — plus confirmation that the Planet imagery pipeline is connected
 * (PLANET_API_KEY) for future automated analysis. Cached 30 days per ticker.
 */
import Anthropic from "@anthropic-ai/sdk";
import { getCached, setCached } from "../store";
import { SYNTH_MODEL } from "../models";
import { result, type Connector, type DetailSection } from "./types";

const meta = { id: "satellite", label: "Satellite Imagery", category: "geo", tier: "premium" } as const;

interface Idea {
  target: string;
  observe: string;
  signal: string;
  cadence: string;
}

const IDEAS_TOOL = {
  name: "emit_satellite_ideas",
  description:
    "Emit concrete, genuinely space-observable satellite-imagery analyses for this specific company that could inform an investment view. Only include things actually visible from commercial satellite imagery (parking/lot fill, construction, storage-tank levels, ship/rail/truck counts, crop/mine activity, thermal/flaring). Be specific to the company's real facilities and sector.",
  input_schema: {
    type: "object" as const,
    properties: {
      ideas: {
        type: "array",
        items: {
          type: "object",
          properties: {
            target: { type: "string", description: "The specific site/asset to image (name a real facility type & location if known)." },
            observe: { type: "string", description: "The measurable feature to track over time." },
            signal: { type: "string", description: "What a change would imply for revenue/production/demand." },
            cadence: { type: "string", description: "How often to image (e.g., weekly, monthly)." },
          },
          required: ["target", "observe", "signal", "cadence"],
        },
      },
      overview: { type: "string", description: "1-2 sentences on how useful satellite is for THIS company and its biggest caveats." },
    },
    required: ["ideas", "overview"],
  },
};

export const satelliteConnector: Connector = {
  ...meta,
  enabled: true,
  description: "Company-specific ideas for evaluating the business from satellite imagery (Planet), with what each would signal.",
  requiredIdentifiers: [],
  async fetch(entity, ctx) {
    const start = Date.now();
    const planetReady = !!process.env.PLANET_API_KEY;
    if (!process.env.ANTHROPIC_API_KEY) {
      return result(meta, { status: "no-data", note: "Satellite analysis ideas require ANTHROPIC_API_KEY.", tookMs: Date.now() - start });
    }
    try {
      let payload = getCached<{ ideas: Idea[]; overview: string }>("satellite", entity.ticker, 1000 * 60 * 60 * 24 * 30);
      if (!payload) {
        const client = new Anthropic({ apiKey: process.env.ANTHROPIC_API_KEY });
        const msg = await client.messages.create({
          model: SYNTH_MODEL,
          max_tokens: 1500,
          tool_choice: { type: "tool", name: IDEAS_TOOL.name },
          tools: [IDEAS_TOOL],
          messages: [
            {
              role: "user",
              content: `Company: ${entity.companyName} (${entity.ticker}). Sector: ${entity.sector ?? "unknown"}. ${entity.description?.slice(0, 400) ?? ""}\n\nPropose satellite-imagery analyses specific to this company. Focus on what's genuinely observable and investment-relevant.`,
            },
          ],
        }, { signal: ctx.signal });
        const tool = msg.content.find((b) => b.type === "tool_use");
        const input = (tool && "input" in tool ? tool.input : {}) as { ideas?: Idea[]; overview?: string };
        payload = { ideas: Array.isArray(input.ideas) ? input.ideas : [], overview: input.overview ?? "" };
        if (payload.ideas.length) setCached("satellite", entity.ticker, payload);
      }
      if (!payload.ideas.length) {
        return result(meta, { status: "no-data", note: "Could not derive satellite analyses for this company.", tookMs: Date.now() - start });
      }

      const detail: DetailSection[] = [
        {
          kind: "keyvals",
          title: "Imagery pipeline",
          items: [
            { label: "Provider", value: "Planet (PlanetScope ~3m daily)" },
            { label: "Status", value: planetReady ? "Connected — key active" : "Not configured (set PLANET_API_KEY)" },
            { label: "Automated CV analysis", value: "Roadmap (v1 is the analysis playbook below)" },
          ],
        },
        {
          kind: "table",
          title: "What to evaluate from space",
          columns: [{ label: "Target" }, { label: "Observe" }, { label: "Signal" }, { label: "Cadence" }],
          rows: payload.ideas.map((i) => ({ cells: [i.target, i.observe, i.signal, i.cadence] })),
          note: payload.overview,
        },
        { kind: "links", title: "Explore imagery", links: [{ label: "Planet Explorer", url: "https://www.planet.com/explorer/" }] },
      ];

      return result(meta, {
        status: "ok",
        headline: `${payload.ideas.length} satellite-analysis ideas for ${entity.companyName}. Planet imagery ${planetReady ? "connected" : "not yet configured"}.`,
        metrics: [
          { name: "Analysis ideas", value: payload.ideas.length },
          { name: "Imagery", value: planetReady ? "Planet ✓" : "not set" },
        ],
        evidence: payload.ideas.slice(0, 3).map((i) => ({ summary: `${i.target} — ${i.observe}` })),
        detail,
        tookMs: Date.now() - start,
      });
    } catch (e) {
      return result(meta, { status: "error", error: e instanceof Error ? e.message : String(e), tookMs: Date.now() - start });
    }
  },
};
