/**
 * Satellite imagery (Planet). Turning imagery into signal is a heavy CV/ML effort, so v1
 * delivers the high-value first step: a company-specific, sector-aware list of WHAT to evaluate
 * from space, WHERE (a real site address + coordinates), and what each observation would signal.
 * Generated by Claude; cached 30 days per ticker.
 *
 * Planet Explorer has no documented coordinate deep-link (login-gated SPA), so each site links to
 * a Google Maps satellite view for an instant look, and the coordinates are shown copy-ready to
 * paste into Planet Explorer's search bar (which builds a ~16km AOI). PLANET_API_KEY confirms the
 * imagery pipeline is connected for future automated analysis.
 */
import Anthropic from "@anthropic-ai/sdk";
import { getCached, setCached } from "../store";
import { SYNTH_MODEL } from "../models";
import { result, type Connector, type DetailSection } from "./types";

const meta = { id: "satellite", label: "Satellite Imagery", category: "geo", tier: "premium" } as const;

interface Idea {
  target: string;
  address: string;
  lat?: number;
  lng?: number;
  observe: string;
  signal: string;
  cadence: string;
}

const IDEAS_TOOL = {
  name: "emit_satellite_ideas",
  description:
    "Emit concrete, space-observable satellite-imagery analyses for this specific company. For each, name a REAL, specific site (its street address or best-known location) and its approximate WGS84 latitude/longitude, what to observe, what a change would signal, and the imaging cadence. Only include things genuinely visible from commercial satellite imagery (lot fill, construction, storage-tank levels, ship/rail/truck counts, crop/mine activity, flaring). If unsure of an exact address, give the best-known facility location and coordinates; never invent a precise street address you are not confident in.",
  input_schema: {
    type: "object" as const,
    properties: {
      ideas: {
        type: "array",
        items: {
          type: "object",
          properties: {
            target: { type: "string", description: "The specific site/asset to image (e.g. 'Fremont Factory — vehicle outbound lots')." },
            address: { type: "string", description: "Real address or best-known location string for that site." },
            lat: { type: "number", description: "Approximate WGS84 latitude of the site." },
            lng: { type: "number", description: "Approximate WGS84 longitude of the site." },
            observe: { type: "string", description: "The measurable feature to track over time." },
            signal: { type: "string", description: "What a change would imply for revenue/production/demand." },
            cadence: { type: "string", description: "How often to image (e.g., weekly, monthly)." },
          },
          required: ["target", "address", "observe", "signal", "cadence"],
        },
      },
      overview: { type: "string", description: "1-2 sentences on how useful satellite is for THIS company and its biggest caveats." },
    },
    required: ["ideas", "overview"],
  },
};

const mapsLink = (lat?: number, lng?: number, address?: string) =>
  lat != null && lng != null
    ? `https://www.google.com/maps/@${lat},${lng},17z/data=!3m1!1e3`
    : `https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(address ?? "")}`;

export const satelliteConnector: Connector = {
  ...meta,
  enabled: true,
  description: "Company-specific ideas for evaluating the business from satellite imagery (Planet), each with a site address and map link.",
  requiredIdentifiers: [],
  async fetch(entity, ctx) {
    const start = Date.now();
    const planetReady = !!process.env.PLANET_API_KEY;
    if (!process.env.ANTHROPIC_API_KEY) {
      return result(meta, { status: "no-data", note: "Satellite analysis ideas require ANTHROPIC_API_KEY.", tookMs: Date.now() - start });
    }
    try {
      let payload = getCached<{ ideas: Idea[]; overview: string }>("satellite2", entity.ticker, 1000 * 60 * 60 * 24 * 30);
      if (!payload) {
        const client = new Anthropic({ apiKey: process.env.ANTHROPIC_API_KEY });
        const msg = await client.messages.create(
          {
            model: SYNTH_MODEL,
            max_tokens: 2000,
            tool_choice: { type: "tool", name: IDEAS_TOOL.name },
            tools: [IDEAS_TOOL],
            messages: [
              {
                role: "user",
                content: `Company: ${entity.companyName} (${entity.ticker}). Sector: ${entity.sector ?? "unknown"}. ${entity.description?.slice(0, 400) ?? ""}\n\nPropose satellite-imagery analyses specific to this company's real facilities, each with a site address + coordinates.`,
              },
            ],
          },
          { signal: ctx.signal }
        );
        const tool = msg.content.find((b) => b.type === "tool_use");
        const input = (tool && "input" in tool ? tool.input : {}) as { ideas?: Idea[]; overview?: string };
        payload = { ideas: Array.isArray(input.ideas) ? input.ideas : [], overview: input.overview ?? "" };
        if (payload.ideas.length) setCached("satellite2", entity.ticker, payload);
      }
      if (!payload.ideas.length) {
        return result(meta, { status: "no-data", note: "Could not derive satellite analyses for this company.", tookMs: Date.now() - start });
      }

      const detail: DetailSection[] = [
        {
          kind: "keyvals",
          title: "Imagery pipeline",
          items: [
            { label: "Provider", value: "Planet (PlanetScope ~3m daily)" },
            { label: "Status", value: planetReady ? "Connected — key active" : "Not configured (set PLANET_API_KEY)" },
            { label: "Automated CV analysis", value: "Roadmap (v1 is the analysis playbook below)" },
          ],
        },
        {
          kind: "table",
          title: "What to evaluate from space — and where",
          columns: [{ label: "Site (click to view)" }, { label: "Observe" }, { label: "Signal" }, { label: "Cadence" }],
          rows: payload.ideas.map((i) => ({
            cells: [
              `${i.target} — ${i.address}${i.lat != null && i.lng != null ? ` (${i.lat.toFixed(3)}, ${i.lng.toFixed(3)})` : ""}`,
              i.observe,
              i.signal,
              i.cadence,
            ],
            href: mapsLink(i.lat, i.lng, i.address),
            hrefLabel: "🛰 View site",
          })),
          note: payload.overview,
        },
        {
          kind: "keyvals",
          title: "Coordinates — paste into Planet Explorer's search bar (builds a ~16 km AOI)",
          items: payload.ideas
            .filter((i) => i.lat != null && i.lng != null)
            .map((i) => ({ label: i.target, value: `${i.lat}, ${i.lng}` })),
        },
        { kind: "links", title: "Open imagery tools", links: [{ label: "Planet Explorer", url: "https://www.planet.com/explorer/", sublabel: "paste a site's coordinates above into the search bar" }] },
      ];

      return result(meta, {
        status: "ok",
        headline: `${payload.ideas.length} satellite-analysis ideas for ${entity.companyName}, each with a site address. Planet imagery ${planetReady ? "connected" : "not yet configured"}.`,
        metrics: [
          { name: "Analysis ideas", value: payload.ideas.length },
          { name: "Sites located", value: payload.ideas.filter((i) => i.lat != null).length },
          { name: "Imagery", value: planetReady ? "Planet ✓" : "not set" },
        ],
        evidence: payload.ideas.slice(0, 3).map((i) => ({ summary: `${i.target} — ${i.address}`, url: mapsLink(i.lat, i.lng, i.address) })),
        detail,
        tookMs: Date.now() - start,
      });
    } catch (e) {
      return result(meta, { status: "error", error: e instanceof Error ? e.message : String(e), tookMs: Date.now() - start });
    }
  },
};
